---
  - name: send email
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ username_email }}"
      password: "{{ password_email }}"
      to: "{{ to_email }}"
      subject: "{{ subject_email }}"
      body: "{{ body_email }}"
    delegate_to: localhost